# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Car": "02_Intro_to_control_theory.ipynb",
         "LinearCar": "02_Intro_to_control_theory.ipynb",
         "step": "03_Transfer_functions.ipynb",
         "delta": "03_Transfer_functions.ipynb",
         "ramp_as_impulses": "02_Intro_to_control_theory.ipynb",
         "ramp": "03_Transfer_functions.ipynb",
         "SimplerCar": "04_Block_Diagrams.ipynb",
         "PendulumParameters": "90_Simple_pendulum.ipynb",
         "Load": "90_Simple_pendulum.ipynb",
         "Pendulum": "90_Simple_pendulum.ipynb",
         "PendulumDrawer": "90_Simple_pendulum.ipynb",
         "AnimatePendulum": "90_Simple_pendulum.ipynb",
         "wrap": "91_DC_motor.ipynb",
         "DCMotorParams": "91_DC_motor.ipynb",
         "DCMotor": "91_DC_motor.ipynb",
         "MotorController": "90_Simple_pendulum.ipynb",
         "AnimateControlledPendulum": "91_DC_motor.ipynb",
         "PID": "91_DC_motor.ipynb",
         "Simulator": "91_DC_motor.ipynb",
         "hide_toggle": "B_Tools.ipynb"}

modules = ["intro_to_control_theory.py",
           "transfer_functions.py",
           "block_diagrams.py",
           "system_response.py",
           "frequency_response.py",
           "steady_state_final_value_theorem.py",
           "routh_hurwitz_criterion.py",
           "nyquist_stability_criterion.py",
           "stability_margins.py",
           "root_locus.py",
           "simple_pendulum.py",
           "dc_motor.py",
           "workspace.py",
           "tools.py"]

doc_url = "https://andreamunafo.github.io/classical_control_theory/"

git_url = "https://github.com/andreamunafo/classical_control_theory/tree/master/"

def custom_doc_links(name): return None
