# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Car": "02_Intro_to_control_theory.ipynb",
         "LinearCar": "02_Intro_to_control_theory.ipynb",
         "step": "03_Transfer_functions.ipynb",
         "delta": "03_Transfer_functions.ipynb",
         "ramp_as_impulses": "02_Intro_to_control_theory.ipynb",
         "ramp": "03_Transfer_functions.ipynb"}

modules = ["intro_to_control_theory.py",
           "transfer_functions.py"]

doc_url = "https://andreamunafo.github.io/classical_control_theory/"

git_url = "https://github.com/andreamunafo/classical_control_theory/tree/master/"

def custom_doc_links(name): return None
