# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://andreamunafo.github.io/classical_control_theory/"

git_url = "https://github.com/andreamunafo/classical_control_theory/tree/master/"

def custom_doc_links(name): return None
