# AUTOGENERATED! DO NOT EDIT! File to edit: 14_Root_locus.ipynb (unless otherwise specified).

__all__ = []

# Cell
import numpy as np
import matplotlib.pyplot as plt
import control

# # To use Latex in matplotlib
# plt.rcParams.update({
#     "text.usetex": False,
#     "font.family": "sans-serif",
#     "font.sans-serif": ["Helvetica"],
#     "font.size": 20})