# AUTOGENERATED! DO NOT EDIT! File to edit: 08_Routh_hurwitz_criterion.ipynb (unless otherwise specified).

__all__ = []

# Cell
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import pandas as pd
import time as systime