# AUTOGENERATED! DO NOT EDIT! File to edit: 03_Transfer_functions.ipynb (unless otherwise specified).

__all__ = ['step', 'ramp', 'delta']

# Cell
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Cell
def step(t, step_time=0):
    """Heaviside step function"""
    return 1 * (t >= step_time) #np.ones((1,len(t))).squeeze()

def ramp(t):
    return t * (t >= 0)

def delta(t, delta_t=0, eps=None):
    if eps is None and len(t) > 1:
        _eps=t[1]-t[0]
    else:
        _eps = eps
    return step(t, delta_t)-step(t, delta_t+_eps)