# AUTOGENERATED! DO NOT EDIT! File to edit: 99_workspace_solution.ipynb (unless otherwise specified).

__all__ = []

# Cell
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.animation as animation

from .simple_pendulum import *
from .dc_motor import *